config/routes.rb
Rails.application.routes.draw do
  namespace :api, format: 'json' do
    namespace :v1 do
      resources :comments, only:[:index]
      resources :posts, only:[:index]
    end
  end

  mount API::Root => '/'

  get 'posts/index'
  get 'posts/new'
  get 'posts/show'
  get 'posts/edit'

  get 'users', to: "users#index"
  get 'users/index'

  post 'follow', to: "relationships#create"
  delete 'unfollow/:user_id', to: "relationships#destroy"

  devise_for :users, :controllers => {
    :sessions => 'users/sessions'
  }

  get 'home/index'
  get 'home/show'

  root to: "posts#index"

  resources :posts do
    resources :comments
    resources :likes, only:[:create], :controller => :post_likes
    delete 'likes', to: 'post_likes#destroy'
  end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  user_id     :integer          not null
#  comment     :text(65535)      not null
#  restriction :integer          not null
#  group_id    :integer          default("0"), not null
#  photo_id1   :integer          default("0"), not null
#  photo_id2   :integer          default("0"), not null
#  photo_id3   :integer          default("0"), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_posts_on_restriction             (restriction)
#  index_posts_on_user_id_and_created_at  (user_id,created_at)
#

class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :likes, class_name: "PostLike", dependent: :destroy
  has_many :liker, through: :likes, source: :user

  validates :user_id, presence: true
  VALID_RESTRICTION_REGEX = /\A0|1|2\z/i
  validates :restriction, presence: true, format: { with: VALID_RESTRICTION_REGEX }
  enum restriction_status: { public_post: 0, follower_only: 1, self_only: 2 } 
  MAX_POSTS_FOR_ONE_PAGE = 20

  def self?(user_id)
    return self.user_id == user_id
  end

  def update_attributes_by_user_id(post_params, user_id)
    if self?(user_id)
      self.update_attributes(post_params)
    else
      errors.add :base, :cant_update_others_post
    end
    return self
  end

  def destroy_by_user_id(user_id)
    if self?(user_id)
      destroy!
    else
      errors.add :base, :cant_destroy_others_post
    end
    return self
  end

  # 全体公開されているpost
  def self.find_public_posts
    posts = Post.where("restriction = ?", Post.restriction_statuses[:public_post]).order(created_at: :desc).limit(MAX_POSTS_FOR_ONE_PAGE).preload(:user)
    return posts
  end

  # 全体公開されているpostと自身の投稿を新しい順に取得
  def self.find_public_posts_and_user_id(user_id)
    posts = Post.all.order(created_at: :desc).limit(MAX_POSTS_FOR_ONE_PAGE).preload(:user)
    filtered_posts = posts.select { |post| post.restriction == restriction_statuses[:public_post] || post.user_id == user_id }
    return filtered_posts
  end

  # 特定のユーザーのフォロワー・全体公開の投稿を新しい順に取得
  def self.find_public_posts_by_user_ids(user_ids)
    posts = Post.where('user_id in (?)', user_ids).from("posts force index(index_posts_on_user_id_and_created_at)").order(created_at: :desc).limit(MAX_POSTS_FOR_ONE_PAGE).preload(:user).preload(:liker)
    filtered_posts = posts.select { |post| post.restriction != restriction_statuses[:self_only] }
    return filtered_posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
    @current_user = current_user
    if current_user.nil?
      @posts = Post.find_public_posts
    else
      user_ids = current_user.following.pluck(:id)
      user_ids.push current_user.id
      @posts = Post.find_public_posts_by_user_ids(user_ids)
    end
  end

  def create
    @post = Post.new(
      user_id: current_user.id,
      comment: params[:post][:comment],
      restriction: params[:post][:restriction])
    @post.save!
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes_by_user_id(post_params, current_user.id)
    if @post.errors.empty?
      respond_to do |format|
        format.html { redirect_to posts_url }
        format.json { head :no_content }
      end
    else
      render 'edit'
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.where('post_id = ?', @post.id).preload(:user)
  end

  def edit
    @post = Post.find(params[:id])
    @comments = Comment.where('post_id = ?', @post.id).preload(:user)
    if !@post.self?(current_user.id)
      @post.errors.add :base, :cant_update_others_post
      render 'show'
      return
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy_by_user_id(current_user.id)
    if @post.errors.empty?
      respond_to do |format|
        format.html { redirect_to posts_url }
        format.json { head :no_content }
      end
    end
  end

  private 
    def post_params
      params.require(:post).permit(:comment, :restriction)
    end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
  .panel-body
    = form_for(@post, html: { role: "form" }) do |f|
      .form-group
        = f.label :comment
        br
        = f.text_field :comment, title: "コメント"
      .form-group
        = f.label :restriction
        br
        = f.radio_button :restriction, 0, {:checked => true}
        = f.label :restriction, "全体公開", value: 0
        = f.radio_button :restriction, 1
        = f.label :restriction, "フォロワーのみ", value: 1
        = f.radio_button :restriction, 2
        = f.label :restriction, "自分のみ", value: 2
      = f.submit("投稿", class: "btn btn-primary")

app/views/posts/create.html.slim
h1 Posts#create
p Find me in app/views/posts/create.html.slim

app/views/posts/destroy.html.slim
h1 Posts#destroy
= error_messages!(@post)
= link_to('戻る', '/posts')

app/views/posts/edit.html.slim
h1 Posts#edit
= error_messages!(@post)
.panel.panel-default.posts
  .panel-heading
    h4 タイムライン編集
  = render 'posts/form'

app/views/posts/index.html.slim
h1 Posts#index
.panel.panel-default.posts
  .panel-heading 投稿一覧
  table.table 
    thead
      tr
        th 投稿者
        th 内容
        th 投稿時間
        th 編集
        th 削除
        th 返信
        th いいね
        th いいね数
        th いいねした人
        th コメント
    tbody
      - @posts.each do |post|
        tr
          td = "#{post.user.last_name}#{post.user.first_name}"
          td = link_to("#{post.comment}", post_path(post))
          td = post.created_at
          td = link_to('編集', edit_post_path(post))
          td = link_to '削除', post, method: :delete, data: { confirm: '本当に削除しますか？' }
          td = link_to('返信する', new_post_comment_path(post))
          - if @current_user.nil?
            td ログインしてください。
          - elsif @current_user.like?(post)
            td = link_to('いいねを外す', post_likes_path(post), method: :delete)
          - else
            td = link_to('いいね', post_likes_path(post), method: :post)
          td = post.likes.count 
          td = react_component( \
            'LikeField', \
            url: "api/v1/posts/#{post.id}/likes.json")
          td 
            .btn.btn-default data-toggle="collapse" href="#collapse-#{post.id}" 表示・非表示
            .collapse[id="collapse-#{post.id}"]
              .well
                = react_component( \
                  'CommentBox', \
                  url: "/api/v1/posts/#{post.id}/comments.json")
.list-group
  .list-group-item
    = link_to '新規投稿', '/posts/new'
  .list-group-item
    = link_to 'ユーザー一覧', '/users'

app/views/posts/new.html.slim
h1 Posts#new
.panel.panel-default.posts
  .panel-heading
    h4 タイムライン投稿
  = render 'posts/form'

= link_to '戻る', '/'

app/views/posts/show.html.slim
h1 Posts#show
= error_messages!(@post)
strong 投稿: #{@post.comment}
br
strong 投稿者: #{@post.user.last_name}#{@post.user.first_name}

h2 Comments
- @comments.each do |comment|
  p コメント投稿者:
    #{comment.user.last_name}#{comment.user.first_name}

  p Comment:
    #{comment.comment}
= link_to('戻る', '/posts')